from __future__ import annotations

from decimal import Decimal


ALERT_RULE_VERSION = "investment-alerts-v1"
DELIVERY_CHANNEL_IN_APP = "IN_APP"

DEFAULT_MINIMUM_SCORE_DELTA = Decimal("5")
DEFAULT_MINIMUM_CONFIDENCE_DELTA = Decimal("10")
DEFAULT_COOLDOWN_MINUTES = 180

MINIMUM_ALLOWED_SCORE_DELTA = Decimal("1")
MINIMUM_ALLOWED_CONFIDENCE_DELTA = Decimal("1")
MINIMUM_COOLDOWN_MINUTES = 30
MAXIMUM_COOLDOWN_MINUTES = 10_080

MAX_ACTIVE_SUBSCRIPTIONS_PER_USER = 20
MAX_SUBSCRIPTIONS_PER_CYCLE = 500
MAX_ALERTS_PER_SUBSCRIPTION_EVALUATION = 4
MAX_ALERTS_PER_CYCLE = 100
MONITORING_RECOMMENDATION_LIMIT = 100

ALERT_TYPE_NEW_OPPORTUNITY = "NEW_OPPORTUNITY"
ALERT_TYPE_ACTION_CHANGE = "ACTION_CHANGE"
ALERT_TYPE_SCORE_CHANGE = "SCORE_CHANGE"
ALERT_TYPE_CONFIDENCE_CHANGE = "CONFIDENCE_CHANGE"
ALERT_TYPE_RISK_CHANGE = "RISK_CHANGE"
ALERT_TYPES = (
    ALERT_TYPE_NEW_OPPORTUNITY,
    ALERT_TYPE_ACTION_CHANGE,
    ALERT_TYPE_SCORE_CHANGE,
    ALERT_TYPE_CONFIDENCE_CHANGE,
    ALERT_TYPE_RISK_CHANGE,
)

SEVERITY_INFO = "INFO"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITIES = (SEVERITY_INFO, SEVERITY_MEDIUM, SEVERITY_HIGH)

VALID_ACTIONS = ("BUY", "WAIT", "AVOID")
OBSERVABLE_ACTIONS = (*VALID_ACTIONS, "NO_RECOMMENDATION")
VALID_RISK_LEVELS = ("LOW", "MEDIUM", "HIGH", "UNKNOWN")
RISK_ORDER = {"UNKNOWN": 0, "LOW": 1, "MEDIUM": 2, "HIGH": 3}
SEVERITY_ORDER = {SEVERITY_HIGH: 3, SEVERITY_MEDIUM: 2, SEVERITY_INFO: 1}
EVENT_PRIORITY = {
    ALERT_TYPE_NEW_OPPORTUNITY: 5,
    ALERT_TYPE_ACTION_CHANGE: 4,
    ALERT_TYPE_RISK_CHANGE: 3,
    ALERT_TYPE_SCORE_CHANGE: 2,
    ALERT_TYPE_CONFIDENCE_CHANGE: 1,
}

# A high-severity event with a different transition is material enough to bypass
# cooldown. The deterministic occurrence key still prevents retry duplicates.
HIGH_SEVERITY_BYPASSES_COOLDOWN = True

