import{useState}from'react';import{useNavigate}from'react-router-dom';import{ArrowRight,BadgeDollarSign,Brain,Gauge,Goal,Landmark,PieChart,ReceiptText,Sparkles,WalletCards}from'lucide-react';import{Button,Card,StatusBadge}from'../components/ui';
const steps=[
{title:'Boas-vindas',desc:'Configure uma visão financeira executiva, clara e conectada.',icon:Sparkles},
{title:'Objetivo financeiro',desc:'Organizar gastos, criar reserva, investir melhor ou reduzir dívidas.',icon:Goal},
{title:'Faixa de renda',desc:'A renda mensal orienta orçamento, metas e alertas.',icon:BadgeDollarSign},
{title:'Modelo financeiro',desc:'Escolha 50/30/20, Base Zero ou modelo personalizado.',icon:Gauge},
{title:'Perfil de gastos',desc:'Separe essenciais, estilo de vida, dívidas e recorrências.',icon:PieChart},
{title:'Meta principal',desc:'Transforme sobra mensal em plano de ação.',icon:Landmark},
{title:'Configuração inicial',desc:'Cadastre contas, cartões, receitas e despesas.',icon:WalletCards},
{title:'Dashboard pronto',desc:'Receba score, diagnóstico e sugestão de investimento.',icon:Brain}
];
export default function Onboarding(){const navigate=useNavigate();const[active,setActive]=useState(0);const StepIcon=steps[active].icon;return <div className="onboarding"><div className="brand-mark"><span className="brand-mark-icon">F</span><span>FinanceOS Startup Grade</span></div><span className="eyebrow" style={{marginTop:28}}>Onboarding premium</span><h1>Seu ERP financeiro pronto para virar rotina diária</h1><p>Uma configuração guiada para conectar receitas, despesas, orçamento, metas, investimentos e diagnóstico financeiro sem parecer ferramenta técnica.</p><div className="progress-steps">{steps.map((_,i)=><span key={i} className={i<=active?'active':''}/>)}</div><div className="grid two"><Card className="glass-panel" interactive><div className="metric-icon"><StepIcon size={22}/></div><span className="step-number">0{active+1}</span><h2>{steps[active].title}</h2><p>{steps[active].desc}</p><div className="quick-actions"><StatusBadge tone="info">Fluxo guiado</StatusBadge><StatusBadge tone="good">Experiência premium</StatusBadge><StatusBadge tone="warn">Sem termos técnicos</StatusBadge></div><div className="form-row"><Button variant="ghost" disabled={active===0} onClick={()=>setActive(v=>Math.max(0,v-1))}>Voltar</Button>{active<steps.length-1?<Button onClick={()=>setActive(v=>Math.min(steps.length-1,v+1))}>Continuar <ArrowRight size={18}/></Button>:<Button onClick={()=>navigate('/')}>Abrir dashboard <ArrowRight size={18}/></Button>}</div></Card><div className="grid two">{steps.map((s,i)=>{const Icon=s.icon;return <Card key={s.title} interactive className={i===active?'tone-good':''}><div className="card-title"><div className="metric-icon"><Icon size={18}/></div><StatusBadge tone={i<active?'good':i===active?'info':'neutral'}>{i<active?'Feito':i===active?'Agora':'Próximo'}</StatusBadge></div><h3>{s.title}</h3><p>{s.desc}</p></Card>})}</div></div></div>}
