import { ReactNode } from 'react';
import { ArrowUpRight, CheckCircle2, CircleAlert, CircleDollarSign, Loader2, Search, Sparkles } from 'lucide-react';
import { money } from '../../utils/format';
import type { Tone } from '../../design-system/tokens';
export function Card({children,className='',interactive=false}:{children:ReactNode;className?:string;interactive?:boolean}){return <section className={`premium-card ${interactive?'interactive-card':''} ${className}`}>{children}</section>}
export function SectionHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="page-header"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function MetricCard({label,value,hint,tone='neutral',icon}:{label:string;value:string|number;hint?:string;tone?:Tone;icon?:ReactNode}){return <Card className={`metric-card tone-${tone}`} interactive><div className="metric-top"><span>{label}</span><div className="metric-icon">{icon??<CircleDollarSign size={18}/>}</div></div><strong>{typeof value==='number'?money(value):value}</strong>{hint&&<small>{hint}</small>}</Card>}
export function StatusBadge({children,tone='neutral'}:{children:ReactNode;tone?:Tone|string}){return <span className={`badge badge-${tone}`}>{children}</span>} export const Badge=StatusBadge;
export function EmptyState({title,message,action}:{title:string;message:string;action?:ReactNode}){return <div className="empty-state"><div className="empty-icon"><Sparkles size={24}/></div><h3>{title}</h3><p>{message}</p>{action&&<div className="empty-action">{action}</div>}</div>}
export function LoadingState({title='Carregando experiência premium...',rows=3}:{title?:string;rows?:number}){return <div className="loading-state"><Loader2 className="spin" size={22}/><strong>{title}</strong>{Array.from({length:rows}).map((_,i)=><span className="skeleton-line" key={i}/>)}</div>}
export function Button({children,variant='primary',className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'ghost'|'danger'|'soft'}){return <button className={`btn btn-${variant} ${className}`} {...props}>{children}</button>} export const PremiumButton=Button;
export function Callout({title,message,tone='info'}:{title:string;message:string;tone?:Tone|string}){const Icon=tone==='danger'?CircleAlert:CheckCircle2;return <div className={`callout callout-${tone}`}><Icon size={18}/><div><strong>{title}</strong><p>{message}</p></div></div>}
export function AlertCard({title,message,tone='info'}:{title:string;message:string;tone?:Tone|string}){return <Card className={`alert-card tone-${tone}`} interactive><Callout title={title} message={message} tone={tone}/></Card>}
export function RecommendationCard({title,message,amount}:{title:string;message:string;amount?:number}){return <Card className="recommendation-card" interactive><div className="rec-icon"><ArrowUpRight size={20}/></div><div><strong>{title}</strong><p>{message}</p>{amount?<span>{money(amount)}</span>:null}</div></Card>}
export function ChartCard({title,children,hint}:{title:string;children:ReactNode;hint?:string}){return <Card className="chart-card"><div className="card-title"><h3>{title}</h3>{hint&&<small>{hint}</small>}</div>{children}</Card>}
export function PremiumTable({children}:{children:ReactNode}){return <div className="table-wrap premium-table"><table>{children}</table></div>}
export function QuickFilter({children}:{children:ReactNode}){return <button className="quick-filter"><Search size={14}/>{children}</button>}
export function PremiumInput(props:React.InputHTMLAttributes<HTMLInputElement>){return <input className="premium-input" {...props}/>} export function PremiumSelect(props:React.SelectHTMLAttributes<HTMLSelectElement>){return <select className="premium-input" {...props}/>} 
